// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class LostLayerRegistered extends ethereum.Event {
  get params(): LostLayerRegistered__Params {
    return new LostLayerRegistered__Params(this);
  }
}

export class LostLayerRegistered__Params {
  _event: LostLayerRegistered;

  constructor(event: LostLayerRegistered) {
    this._event = event;
  }

  get id_(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get address_(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class LostLayerUnregistered extends ethereum.Event {
  get params(): LostLayerUnregistered__Params {
    return new LostLayerUnregistered__Params(this);
  }
}

export class LostLayerUnregistered__Params {
  _event: LostLayerUnregistered;

  constructor(event: LostLayerUnregistered) {
    this._event = event;
  }

  get id_(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get address_(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class RoleAdminChanged extends ethereum.Event {
  get params(): RoleAdminChanged__Params {
    return new RoleAdminChanged__Params(this);
  }
}

export class RoleAdminChanged__Params {
  _event: RoleAdminChanged;

  constructor(event: RoleAdminChanged) {
    this._event = event;
  }

  get role(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get previousAdminRole(): Bytes {
    return this._event.parameters[1].value.toBytes();
  }

  get newAdminRole(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }
}

export class RoleGranted extends ethereum.Event {
  get params(): RoleGranted__Params {
    return new RoleGranted__Params(this);
  }
}

export class RoleGranted__Params {
  _event: RoleGranted;

  constructor(event: RoleGranted) {
    this._event = event;
  }

  get role(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get account(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get sender(): Address {
    return this._event.parameters[2].value.toAddress();
  }
}

export class RoleRevoked extends ethereum.Event {
  get params(): RoleRevoked__Params {
    return new RoleRevoked__Params(this);
  }
}

export class RoleRevoked__Params {
  _event: RoleRevoked;

  constructor(event: RoleRevoked) {
    this._event = event;
  }

  get role(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }

  get account(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get sender(): Address {
    return this._event.parameters[2].value.toAddress();
  }
}

export class LostLayer extends ethereum.SmartContract {
  static bind(address: Address): LostLayer {
    return new LostLayer("LostLayer", address);
  }

  DEFAULT_ADMIN_ROLE(): Bytes {
    let result = super.call(
      "DEFAULT_ADMIN_ROLE",
      "DEFAULT_ADMIN_ROLE():(bytes32)",
      []
    );

    return result[0].toBytes();
  }

  try_DEFAULT_ADMIN_ROLE(): ethereum.CallResult<Bytes> {
    let result = super.tryCall(
      "DEFAULT_ADMIN_ROLE",
      "DEFAULT_ADMIN_ROLE():(bytes32)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  REGISTER_ROLE(): Bytes {
    let result = super.call("REGISTER_ROLE", "REGISTER_ROLE():(bytes32)", []);

    return result[0].toBytes();
  }

  try_REGISTER_ROLE(): ethereum.CallResult<Bytes> {
    let result = super.tryCall(
      "REGISTER_ROLE",
      "REGISTER_ROLE():(bytes32)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  UNREGISTER_ROLE(): Bytes {
    let result = super.call(
      "UNREGISTER_ROLE",
      "UNREGISTER_ROLE():(bytes32)",
      []
    );

    return result[0].toBytes();
  }

  try_UNREGISTER_ROLE(): ethereum.CallResult<Bytes> {
    let result = super.tryCall(
      "UNREGISTER_ROLE",
      "UNREGISTER_ROLE():(bytes32)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  compass(id_: Bytes): Address {
    let result = super.call("compass", "compass(bytes32):(address)", [
      ethereum.Value.fromFixedBytes(id_)
    ]);

    return result[0].toAddress();
  }

  try_compass(id_: Bytes): ethereum.CallResult<Address> {
    let result = super.tryCall("compass", "compass(bytes32):(address)", [
      ethereum.Value.fromFixedBytes(id_)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  compassKeys(): Array<Bytes> {
    let result = super.call("compassKeys", "compassKeys():(bytes32[])", []);

    return result[0].toBytesArray();
  }

  try_compassKeys(): ethereum.CallResult<Array<Bytes>> {
    let result = super.tryCall("compassKeys", "compassKeys():(bytes32[])", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytesArray());
  }

  getAddressFromPath(path: Array<Bytes>): Address {
    let result = super.call(
      "getAddressFromPath",
      "getAddressFromPath(bytes32[]):(address)",
      [ethereum.Value.fromFixedBytesArray(path)]
    );

    return result[0].toAddress();
  }

  try_getAddressFromPath(path: Array<Bytes>): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "getAddressFromPath",
      "getAddressFromPath(bytes32[]):(address)",
      [ethereum.Value.fromFixedBytesArray(path)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getRoleAdmin(role: Bytes): Bytes {
    let result = super.call("getRoleAdmin", "getRoleAdmin(bytes32):(bytes32)", [
      ethereum.Value.fromFixedBytes(role)
    ]);

    return result[0].toBytes();
  }

  try_getRoleAdmin(role: Bytes): ethereum.CallResult<Bytes> {
    let result = super.tryCall(
      "getRoleAdmin",
      "getRoleAdmin(bytes32):(bytes32)",
      [ethereum.Value.fromFixedBytes(role)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  getRoleMember(role: Bytes, index: BigInt): Address {
    let result = super.call(
      "getRoleMember",
      "getRoleMember(bytes32,uint256):(address)",
      [
        ethereum.Value.fromFixedBytes(role),
        ethereum.Value.fromUnsignedBigInt(index)
      ]
    );

    return result[0].toAddress();
  }

  try_getRoleMember(role: Bytes, index: BigInt): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "getRoleMember",
      "getRoleMember(bytes32,uint256):(address)",
      [
        ethereum.Value.fromFixedBytes(role),
        ethereum.Value.fromUnsignedBigInt(index)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getRoleMemberCount(role: Bytes): BigInt {
    let result = super.call(
      "getRoleMemberCount",
      "getRoleMemberCount(bytes32):(uint256)",
      [ethereum.Value.fromFixedBytes(role)]
    );

    return result[0].toBigInt();
  }

  try_getRoleMemberCount(role: Bytes): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "getRoleMemberCount",
      "getRoleMemberCount(bytes32):(uint256)",
      [ethereum.Value.fromFixedBytes(role)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  hasRole(role: Bytes, account: Address): boolean {
    let result = super.call("hasRole", "hasRole(bytes32,address):(bool)", [
      ethereum.Value.fromFixedBytes(role),
      ethereum.Value.fromAddress(account)
    ]);

    return result[0].toBoolean();
  }

  try_hasRole(role: Bytes, account: Address): ethereum.CallResult<boolean> {
    let result = super.tryCall("hasRole", "hasRole(bytes32,address):(bool)", [
      ethereum.Value.fromFixedBytes(role),
      ethereum.Value.fromAddress(account)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  supportsInterface(interfaceId: Bytes): boolean {
    let result = super.call(
      "supportsInterface",
      "supportsInterface(bytes4):(bool)",
      [ethereum.Value.fromFixedBytes(interfaceId)]
    );

    return result[0].toBoolean();
  }

  try_supportsInterface(interfaceId: Bytes): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "supportsInterface",
      "supportsInterface(bytes4):(bool)",
      [ethereum.Value.fromFixedBytes(interfaceId)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }
}

export class GrantRoleCall extends ethereum.Call {
  get inputs(): GrantRoleCall__Inputs {
    return new GrantRoleCall__Inputs(this);
  }

  get outputs(): GrantRoleCall__Outputs {
    return new GrantRoleCall__Outputs(this);
  }
}

export class GrantRoleCall__Inputs {
  _call: GrantRoleCall;

  constructor(call: GrantRoleCall) {
    this._call = call;
  }

  get role(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get account(): Address {
    return this._call.inputValues[1].value.toAddress();
  }
}

export class GrantRoleCall__Outputs {
  _call: GrantRoleCall;

  constructor(call: GrantRoleCall) {
    this._call = call;
  }
}

export class InitializeCall extends ethereum.Call {
  get inputs(): InitializeCall__Inputs {
    return new InitializeCall__Inputs(this);
  }

  get outputs(): InitializeCall__Outputs {
    return new InitializeCall__Outputs(this);
  }
}

export class InitializeCall__Inputs {
  _call: InitializeCall;

  constructor(call: InitializeCall) {
    this._call = call;
  }

  get admin(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class InitializeCall__Outputs {
  _call: InitializeCall;

  constructor(call: InitializeCall) {
    this._call = call;
  }
}

export class RegisterLostLayerCall extends ethereum.Call {
  get inputs(): RegisterLostLayerCall__Inputs {
    return new RegisterLostLayerCall__Inputs(this);
  }

  get outputs(): RegisterLostLayerCall__Outputs {
    return new RegisterLostLayerCall__Outputs(this);
  }
}

export class RegisterLostLayerCall__Inputs {
  _call: RegisterLostLayerCall;

  constructor(call: RegisterLostLayerCall) {
    this._call = call;
  }

  get id_(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get address_(): Address {
    return this._call.inputValues[1].value.toAddress();
  }
}

export class RegisterLostLayerCall__Outputs {
  _call: RegisterLostLayerCall;

  constructor(call: RegisterLostLayerCall) {
    this._call = call;
  }
}

export class RenounceRoleCall extends ethereum.Call {
  get inputs(): RenounceRoleCall__Inputs {
    return new RenounceRoleCall__Inputs(this);
  }

  get outputs(): RenounceRoleCall__Outputs {
    return new RenounceRoleCall__Outputs(this);
  }
}

export class RenounceRoleCall__Inputs {
  _call: RenounceRoleCall;

  constructor(call: RenounceRoleCall) {
    this._call = call;
  }

  get role(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get account(): Address {
    return this._call.inputValues[1].value.toAddress();
  }
}

export class RenounceRoleCall__Outputs {
  _call: RenounceRoleCall;

  constructor(call: RenounceRoleCall) {
    this._call = call;
  }
}

export class RevokeRoleCall extends ethereum.Call {
  get inputs(): RevokeRoleCall__Inputs {
    return new RevokeRoleCall__Inputs(this);
  }

  get outputs(): RevokeRoleCall__Outputs {
    return new RevokeRoleCall__Outputs(this);
  }
}

export class RevokeRoleCall__Inputs {
  _call: RevokeRoleCall;

  constructor(call: RevokeRoleCall) {
    this._call = call;
  }

  get role(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get account(): Address {
    return this._call.inputValues[1].value.toAddress();
  }
}

export class RevokeRoleCall__Outputs {
  _call: RevokeRoleCall;

  constructor(call: RevokeRoleCall) {
    this._call = call;
  }
}

export class UnregisterLostLayerCall extends ethereum.Call {
  get inputs(): UnregisterLostLayerCall__Inputs {
    return new UnregisterLostLayerCall__Inputs(this);
  }

  get outputs(): UnregisterLostLayerCall__Outputs {
    return new UnregisterLostLayerCall__Outputs(this);
  }
}

export class UnregisterLostLayerCall__Inputs {
  _call: UnregisterLostLayerCall;

  constructor(call: UnregisterLostLayerCall) {
    this._call = call;
  }

  get id_(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }
}

export class UnregisterLostLayerCall__Outputs {
  _call: UnregisterLostLayerCall;

  constructor(call: UnregisterLostLayerCall) {
    this._call = call;
  }
}
